services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: deepwiki-backend
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ~/.adalflow:/root/.adalflow      # Persist repository and embedding data
      - ./backend/api/logs:/app/api/logs # Persist log files across container restarts
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8001/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - SERVER_BASE_URL=http://backend:8001
    container_name: deepwiki-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - SERVER_BASE_URL=http://backend:8001
    depends_on:
      backend:
        condition: service_healthy

networks:
  default:
    driver: bridge
