version: '3.8'

services:
  deepwiki:
    build: .
    ports:
      - "8001:8001"  # API port
      - "3000:3000"  # Next.js port
    env_file:
      - .env
    environment:
      - PORT=8001
      - NODE_ENV=production
    volumes:
      - ~/.adalflow:/root/.adalflow  # Persist repository and embedding data
