model_list:
  # -----------------------
  # Chat / Generation models
  # -----------------------
  - model_name: ark-code-latest
    litellm_params:
      model: openai/ark-code-latest
      api_base: https://ark.cn-beijing.volces.com/api/coding/v3
      api_key: os.environ/LITELLM_ARK_API_KEY

  - model_name: deepseek-v4-flash-260425
    litellm_params:
      model: openai/deepseek-v4-flash-260425
      api_base: https://ark.cn-beijing.volces.com/api/coding/v3
      api_key: os.environ/LITELLM_ARK_API_KEY

  - model_name: crs
    litellm_params:
      model: openai/gpt5.5
      api_base: http://47.101.159.7:39187/v1
      api_key: os.environ/LITELLM_CRS_API_KEY

litellm_settings:
  set_verbose: true
  drop_params: true
