name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=short
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.title=DeepWiki Open
            org.opencontainers.image.description=AI-Powered Wiki Generator for GitHub/GitLab/Bitbucket Repositories
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Create empty .env file for build
        run: touch .env

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Make package public when merged to main branch
      - name: Make package public
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Wait a moment for the package to be available
          sleep 10
          
          # Extract owner and repo name
          OWNER=$(echo "${{ github.repository }}" | cut -d '/' -f 1)
          REPO=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          PACKAGE_NAME=$(echo "$REPO" | tr '[:upper:]' '[:lower:]')

          # Use GitHub CLI to set package visibility to public
          echo "Setting package visibility to public..."
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            "/user/packages/container/$PACKAGE_NAME/visibility" \
            -f visibility=public || \
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            "/orgs/$OWNER/packages/container/$PACKAGE_NAME/visibility" \
            -f visibility=public
